### ISSUE TITLE
sample tampered log files?

### ISSUE THREAD

**Issue by williballenthin** [fox-it/danderspritz-evtx#1]
To demonstrate the efficacy of this script, would you publish some test .evtx log files that we can inspect?

**Comment by fox-srt** [comment]
Hi  Willi,
Just to let you know, we are working on it. Expect it soon in the repo :)

**Comment by fox-srt** [comment]
Hi Willi,

We updated the repo with an example evtx modified with Danderspritz eventlogedit.

**Comment by williballenthin** [comment]
awesome, thanks @fox-srt !
